// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrientPyx.DataAccess.Persistence;

#nullable disable

namespace OrientPyx.DataAccess.Persistence.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("OrientPyx.BusinessLogic.Entities.AppSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("A4PrinterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventsPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FontScale")
                        .HasColumnType("REAL");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OnlineIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OnlinePublicBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OnlineServiceRoleKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OnlineSupabaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RankCountForRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankMinParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankMinRegions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReadoutType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiptWidthMm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultProtocolJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartProtocolJudgesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartProtocolRegularJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatementJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("OrientPyx.BusinessLogic.Entities.LastSessionRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastEventDayNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastEventIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LastSession");
                });

            modelBuilder.Entity("OrientPyx.BusinessLogic.Entities.PointsRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formula")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"Name\" <> ''");

                    b.ToTable("PointsRules");
                });

            modelBuilder.Entity("OrientPyx.BusinessLogic.Entities.RankQualificationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PointsFirst")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PointsKms")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PointsSecond")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PointsThird")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PointsThirdJunior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeFirst")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeKms")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeSecond")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeThird")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeThirdJunior")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RankQualification");
                });

            modelBuilder.Entity("OrientPyx.BusinessLogic.Entities.SportRank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Points")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"Name\" <> ''");

                    b.ToTable("Ranks");
                });
#pragma warning restore 612, 618
        }
    }
}
